library(gplots)
library(dplyr)

args = commandArgs(trailingOnly=TRUE)

#Here, set the file name of the table generated by get_seq_lengths.py (= compiled_paralogs.txt from joined hp2.py)
sample.filename = args[1]

sample.data= as.matrix(read.table(sample.filename,header=T,row.names=1,sep="\t",fill=T))
renames <- c(colnames(sample.data)[2:length(colnames(sample.data))], "NAS")
colnames(sample.data) <- renames
sample.data <- sample.data[,colnames(sample.data) != "NAS"]

breaks = seq(0,max(sample.data),length.out=max(sample.data)*4)
gradient1 = colorpanel( sum( breaks[-1]<=1.5 ), "#FFFFFF","#132B43")
gradient2 = colorpanel( sum( breaks[-1]>=2 ), "yellow", "red" )
hm.colors = c(gradient1,gradient2)

pdf(file = "combined_results/paralog_heatmap.pdf", height = 8.3, width = 11.7, colormodel="cmyk")
heatmap.2(sample.data, dendrogram = "none", trace = 'none',
          tracecol = "black", key = T, keysize = 1, col = hm.colors,
          cexCol = nrow(sample.data)*0.001, cexRow = ncol(sample.data)*0.001)
dev.off()

# Quick part to get file with genes with 1 or less paralogs
x<-as.data.frame(sample.data)
a<-x %>% select(where(~all( .x <= 1)))
b<-x %>% select(where(~all( .x == 1)))
c<-x %>% select(where(~all( .x <= 3)))
a<-colnames(a)
b<-colnames(b)
c<-colnames(c)
a<-gsub("X","",a)
b<-gsub("X","",b)
c<-gsub("X","",c)

n <- max(length(a), length(b), length(c))
length(a) <- n                      
length(b) <- n
length(c) <- n

df<-cbind(a, b, c)
colnames(df)<-c("Paralogs = 0-1", "Paralogs = 1", "Paralogs = 0-3") 
#df<-df[is.na(df)] <- ""

write.table(df, "combined_results/paralog_free_genes.txt", sep = "\t", row.names = FALSE)
#fileConn<-file("combined_results/paralog_free_genes.txt")
#writeLines(y, fileConn)
#close(fileConn)