library(ggplot2)
library(ggrepel)
library(reshape2)

args = commandArgs(trailingOnly=TRUE)

#Here, set the file name of the table generated by get_seq_lengths.py (= all_lengths.txt from joined hp2.py on Gadi)
sample.filename = args[1]

sample.data= as.matrix(read.table(sample.filename,header=T,row.names=1,sep="\t",fill=T))
renames <- c(colnames(sample.data)[2:length(colnames(sample.data))], "NAS")
colnames(sample.data) <- renames
sample.data <- sample.data[,colnames(sample.data) != "NAS"]
sample.len = sample.data[2:nrow(sample.data),]
reference.len = as.numeric(sample.data[1,])

# Calculate mean length for all genes and refs (intended to provide quick visualization of failed samples)
sample_mean_recovered_length <- as.data.frame(rowMeans(sample.len))
reference_mean_recovered_length <- mean(reference.len)

# Find outliers using IQR criterion
outliers <- boxplot.stats(rowMeans(sample.len))$out

# Formatting dataframe for plotting
colnames(sample_mean_recovered_length) <- "means"
sample_mean_recovered_length$outlier <- "no"
sample_mean_recovered_length$outlier[match(names(outliers), row.names(sample_mean_recovered_length))] <- "yes"

if (any(sample_mean_recovered_length$outlier == "yes")) {
  ggplot() +
    geom_histogram(data = sample_mean_recovered_length,
                   aes(x = means, fill = outlier),
                   bins = length(row.names(sample_mean_recovered_length))/3) +
    geom_text_repel(data = subset(sample_mean_recovered_length, outlier == "yes"),
                    aes(x = means, y = 5,
                        label = row.names(subset(sample_mean_recovered_length, outlier == "yes"))),
                    size = 2, angle = 90,
                    force = 0.00005,
                    direction = "x",
                    hjust = 0) +
    scale_fill_manual(values = c("light blue", "#D60000")) +
    geom_vline(xintercept = reference_mean_recovered_length, size = 1.5) +
    xlab("Mean gene length") + ylab(NULL) + coord_cartesian(expand = FALSE) +
    theme_linedraw() 
} else {
  sample_mean_recovered_length$outlier[sample_mean_recovered_length$means < 400] <- "yes"
  colnames(sample_mean_recovered_length)[2] <- "< 400 bp"
  ggplot() +
    geom_histogram(data = sample_mean_recovered_length,
                   aes(x = means, fill = `< 400 bp`),
                   bins = length(row.names(sample_mean_recovered_length))/3) +
    geom_text_repel(data = subset(sample_mean_recovered_length, `< 400 bp` == "yes"),
                    aes(x = means, y = 5,
                        label = row.names(subset(sample_mean_recovered_length, `< 400 bp` == "yes"))),
                    size = 2, angle = 90,
                    force = 0.00005,
                    direction = "x",
                    hjust = 0) +
    scale_fill_manual(values = c("light blue", "#D60000")) +
    geom_vline(xintercept = reference_mean_recovered_length, size = 1.5) +
    xlab("Mean gene length") + ylab(NULL) + coord_cartesian(expand = FALSE) +
    theme_linedraw()
}

ggsave("combined_results/sample_histogram.png", height = 21, width = 29.7, units = "cm") 
write.table(sample_mean_recovered_length, "combined_results/mean_gene_lengths.txt", sep = "\t")